### ISSUE TITLE
Inserter configuration mode errors

### ISSUE THREAD

**Issue by SGZ-Creations** [modded-factorio/bobsmods#201] opened 2024-10-23 22:38 UTC
![image](https://github.com/user-attachments/assets/7a7604db-2601-4474-a178-ca1ff3c6b84c)
![image](https://github.com/user-attachments/assets/e04ee0ff-8a63-446a-a2e5-7a8d4db9d2d9)
![image](https://github.com/user-attachments/assets/79ea0a45-e2a1-44aa-8b58-be43dbd2b49c)

**Comment by TehFocus** [comment] 2024-10-24 16:46
I can confirm this issue.

**Steps  to reproduce:**
1. Place inserter facing north
2. Place inserter facing east
3. Configure first inserter via the mods menu
4. Shift + Right Mousebutton to copy inserter settings from the configured inserter
5. Shift + Left Mousebutton to paste settings unto second inserter

The instructions pasted will correspond to the orientation of the inserter, not the positions from the copied inserter. (What was facing north on the original, will face east on the second inserter)

This could be considered working as intended, as it correctly corresponds to the way the inserter was placed, but I would strongly disagree to keep it like this, as it requires more user input to get an inserter to orient the way he wants.



**Possible solution:**
Copy not only bobs adjustable inserter settings but also the orientation of the original inserter.

**Comment by Qatavin** [comment] 2024-10-25 02:23
That sounds like 100% intended behavior. If you have a blueprint, obviously you would want to have your inserters still pointing at the correct targets if the blueprint was rotated. On an intuitive level, copy and pasting a single inserter should work the same way, and copy and pasting the configuration of a single inserter should as well.

**Comment by KiwiHawk** [comment] 2024-10-25 03:28
It's interesting, must have been some base game change that caused the discrepancy. I wonder what and why? 🤔

**Comment by Neamow** [comment] 2024-10-25 18:34
Don't even need to mess with blueprints, the inserters just straight up place wrong even manually.

Place one going west-east, it places south-north. Rotate it to the right spot, copy it, it's placed north-south by a robot. It's totally broken unfortunately.

https://www.youtube.com/watch?v=upGsvAKZbu4

**Comment by KiwiHawk** [comment] 2024-10-25 22:20
Sounds like it may actually be a base game bug

**Comment by KiwiHawk** [comment] 2024-10-28 00:11
Fixed in v1.3.1

**Comment by KiwiHawk** [comment] 2024-10-28 01:24
Fixed in v1.3.1
Inserter configuration mode will not affect ghosts. Maybe I'll find a way to add this in the future. I'm okay without it for now (same behaviour as placing ghosts in 1.1)

**Comment by SGZ-Creations** [comment] 2024-10-28 06:04
After the last fix the pickup and place is inverted not sure why

**Comment by KiwiHawk** [comment] 2024-10-28 11:02
Fixed in v1.3.2
Placing ghost insterters should now respect inserter configuration mode!

**Closed by KiwiHawk** 2024-10-28 11:02 UTC
Labels: bug, Bob's Adjustable Inserters, Factorio 2.0
