### ISSUE TITLE
Bob's Adjustable Inserters - Inserter window dock position: Off - uses previous dock position

### ISSUE THREAD

**Issue by Izen5781** [modded-factorio/bobsmods#55] opened 2022-08-06 20:39 UTC
When I change the "Inserter window dock position" player setting to "Off", the configuration window still appears when clicking an inserter. It uses whatever dock position I had selected before I changed the dropdown to "Off". Edit: If I start a new world with the "Inserter window dock position" player setting set to "Off", the configuration does not appear when clicking an inserter (AKA works as intended).

Factorio Version: 1.1.61 (build 59839, win64)

**Comment by KiwiHawk** [comment] 2023-01-01 23:22
Are you still able to reproduce this? I can't. The latest version of Adjustable Inserters (1.1.6) did have some changes related to this so I'm wondering if it's been fixed by accident?

**Comment by Izen5781** [comment] 2023-01-02 16:35
@KiwiHawk I am still able to reproduce the issue on the latest version of Factorio (1.1.74, build 60256, win64) with the latest version of Bob's Adjustable Inserters (1.1.7).

This is what I did to reproduce the issue just now:
* Update mods so only "Bob's Adjustable Inserters mod" is enabled.
* From the main menu go to: Settings -> Mod settings -> Per player tab -> reset settings to their defaults, then click Confirm.
* Start a new "Sandbox" game.
* Say yes to all 4 prompts (All Tech, Items, Cheat mode, Always day). 
* Place a yellow inserter.
* Click the yellow inserter. (Inserter configuration is visible on the right.)
* Press "Esc" twice to get to the Game menu.
* Go to: Settings -> Mod settings -> Per player tab -> change "Inserter window dock position" to "Off", then click Confirm.
* Press "Esc" twice to get back into the game.
* Click the yellow inserter. (Inserter configuration is still visible on the right.)

**Comment by KiwiHawk** [comment] 2023-01-03 01:03
Excellent reproduction steps! Thank you. I wish all bug reports were as good!

Turns out it was an easy fix :-) I don't think I need to put out a new release just to fix this though.

**Comment by Izen5781** [comment] 2023-01-03 04:36
No problem! And awesome! I'm glad it was an easy fix.

**Closed** 2023-01-03 08:39 UTC
Labels: bug, Bob's Adjustable Inserters
